# This workflow will test, build and deploy a Unity Project

name: Unity CI

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  activate:
    name: Activate Unity License
    runs-on: ubuntu-22.04
    env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    steps:
      - uses: game-ci/unity-activate@v2